### ISSUE TITLE
Report Job Board listings without need to DM a moderator, using: !report <messageID>

### ISSUE THREAD

**Issue by slimsons** [unreal-slackers/manny#97]
### **Is your feature request related to a problem? Please describe.**

Job board listings are often times incorrectly posted. 

Such as posting a rev-share "looking for team"/recruitment post, to #hire-a-studio

Another example is posting in #permanent-jobs, that you are trying to find a programmer for your video game, but compensation is rev-share when/if the game is released, when there is no studio or entity established. 

As of writing this, both of these examples currently exist in the Job Board. 

### **Describe the solution you'd like**

Send a DM to Manny: 

`!report messageID` 

With the message ID of the Job Board listing in question. 

(This command will **only** work for messages in channels, under the Job Board category.)

After sending Manny `!report messageID` , either:

- Manny simply replies, `Report successful. Thank you for helping the community!` - or something like that.

_or_

- Manny replies: 
```
Reply with the number that corresponds best with your reason for report:

1. Trolling

2. Misleading

3. Incorrect compensation for channel
```

(Of course if going this route, moderators would decide the reasons)

After selecting a number, Manny would reply, `Report successful. Thank you for helping the community!` - or something like that.

Then Manny would send a message to a mods-only, read-only private channel:

```
"(Listing) {messageIDHyperlink} has been reported".

Reports: 2
```

If more users were to report the same listing, Manny would just edit the message in the read-only channel, and increment the Report count from 1 to 2, and so on. Here is a report from Manny using the number-per-reason method.

```
"(Listing) {messageIDHyperlink} has been reported".

Trolling: 3
Incorrect compensation for channel: 2
Misleading: 0
Total Reports: 5 
```

This way, moderators could simply check the channels as they have time. 
If desired, you could have Manny ping the moderator role after 5 or 7 reports has been reached.

Additionally, I thought a cool feature to this might be the ability to close an open report, by clicking on a react emoji. Maybe a ❌if it's deemed the reports are unnecessary, then Manny will "collapse" the message by editing it to `(Listing) {messageIDHyperlink} has been approved by moderators` , and any further reports on that listings message ID will be ignored. 

To get a message ID, a user would need to enable developer mode for discord to right click a message to copy its ID. Alternatively they could copy the message URL, which contains the message ID. I think this will deter most users for reporting listings just to be a troll. 

If you send Manny a `!report` with a message ID that _is not_ within the Job Board category, Manny will simply not reply, or reply with `Invalid command`

### **Describe alternatives you've considered**
I described 2 different behaviors for Manny in the above section, but the obvious alternative would be to just DM a moderator, or just tag one in one of the servers. But that's no fun is it?

### **Additional context**
While some may think it to be superfluous, I think that it would make a very nice convivence feature for moderators, get the ball rolling on community collaboration, and it would of course be an honor to add functionality to Manny! Cheers community!

**Comment by pfist** [comment]
Thanks for the thorough proposal. The mods and I are discussing it, and we'll let you know if we want to move forward with this.

**Comment by pfist** [comment]
We recently added a "Report to Moderators" command that largely addresses this request. Thanks again for the suggestion @slimsons! If you want to suggest improvements, it's part of our new bot, [Quinn](https://github.com/unreal-slackers/quinn).
